org: dbkompare
app: db-kompare
service: serverless-python
configValidationMode: error

provider:
  name: aws
  runtime: python3.12
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  profile: dbkompare

functions:
  hello:
    handler: functions/profiling.handler
    events:
      - httpApi:
          path: /
          method: get
