org: dbkompare
app: db-kompare
service: db-kompare-resources
configValidationMode: error

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  profile: dbkompare

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: db-kompare-users-${self:provider.stage}
        KeySchema:
          - AttributeName: id
            KeyType: HASH # Primary partition key
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S # String type for id (primary key)
          - AttributeName: status
            AttributeType: S # String type for status
          - AttributeName: role
            AttributeType: S # String type for role
        GlobalSecondaryIndexes:
          - IndexName: byStatusandRole
            KeySchema:
              - AttributeName: status # Partition key for the GSI
                KeyType: HASH
              - AttributeName: role # Sort key for the GSI
                KeyType: RANGE
            Projection:
              ProjectionType: ALL # Include all attributes in the index
        BillingMode: PAY_PER_REQUEST
    Databases:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: db-kompare-databases-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: status
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: byStatus
            KeySchema:
              - AttributeName: status
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    Metrices:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: db-kompare-metrices-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: database_id
            AttributeType: S
          - AttributeName: date
            AttributeType: S
          - AttributeName: includeMe
            AttributeType: S
        KeySchema:
          - AttributeName: database_id
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: byStatusAndDate
            KeySchema:
              - AttributeName: includeMe
                KeyType: HASH
              - AttributeName: date
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    DatabaseRankings:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: db-kompare-database-rankings-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: date
            AttributeType: S
          - AttributeName: includeMe
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: byStatusAndDate
            KeySchema:
              - AttributeName: includeMe
                KeyType: HASH
              - AttributeName: date
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
